ALTER TABLE "Client"
  ALTER COLUMN "firstName" TYPE VARCHAR(25),
  ALTER COLUMN "lastName" TYPE VARCHAR(25),
  ALTER COLUMN "documentId" TYPE VARCHAR(11),
  ALTER COLUMN "phone" TYPE VARCHAR(10),
  ALTER COLUMN "address" TYPE VARCHAR(50);